name: Continuous Integration
run-name: ${{ github.actor }} started workflow
on: [push]
branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
          cache: maven
      - name: Run and Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Run Tests
        run: mvn --batch-mode --update-snapshots test
      - run: mkdir staging && cp target/*.jar staging
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: target/*.jar